spring:
  application:
    name: banco-digital-api
  jackson:
    deserialization:
      fail-on-unknown-properties: true

server:
  port: 8088

springdoc:
  packagesToScan: com.bancodigital.api.controller
